SERVER_HOST: "localhost"
SERVER_PORT: 5001
BUFFER_SIZE: 4096
SEPARATOR: '\t'
BLOCK_SIZE: 32
RECURSIVE: false
MODE: 1
TARGET_FILE: "small.txt"
# ABSOLUTEPATH: ""
# PILIHAN MODE
# MODE_ECB = 1
# MODE_CBC = 2
# MODE_CFB = 3
# MODE_OFB = 5
# MODE_CTR = 6
