SERVER_HOST: "localhost"
SERVER_PORT: 5001
BUFFER_SIZE: 4096
SEPARATOR: '\t'
RECURSIVE: false
METHOD: RC4lib
MODE: 6
TARGET_FILE: "big.txt"
ABSOLUTEPATH: "/home/allam/dev-project/kij"
# PILIHAN MODE
# MODE_ECB = 1
# MODE_CBC = 2
# MODE_CFB = 3
# MODE_OFB = 5
# MODE_CTR = 6